### ISSUE TITLE
Link issue and Contact Us design

### ISSUE THREAD

**Issue by Muhammad-Anus-Developer** [Ayushgupta0207/HacktoberFest-2023#10]
Hi @Ayushgupta0207, I have found that the links on the navbar are not working.

If you will assign me the task I would fix the links and improve the design of contact us page.

**Comment by Ayushgupta0207** [comment]
Sure

**Comment by NiranjanLangade** [comment]
Hi ! I can solve this issue please assign me

**Comment by Shankar009378** [comment]
Hi Sir,  I can solve this issue please assign me.

**Comment by Ayushgupta0207** [comment]
You can fork the repo and make the changes and create a pull request , I will merge it for sure

**Comment by Shankar009378** [comment]
Sir I have done this link issue and contact us design please check my
github id:- https://github.com/Shankar009378

**Comment by Ayushgupta0207** [comment]
You can check I will merge the repo

**Comment by Ayushgupta0207** [comment]
@NiranjanLangade pls create a pull request

**Comment by Shankar009378** [comment]
Done.

**Comment by NiranjanLangade** [comment]
I have created a pull request please merge it
