### ISSUE TITLE
Bug 🐛:  Unnecessary 'About' Link and Duplicate 'Home' in Nav.

### ISSUE THREAD

**Issue by mohit-100** [Ayushgupta0207/HacktoberFest-2023#19]
**Bug Description:**

When I click on the "Home" link in the navigation menu, it unexpectedly creates a duplicate "Home" link, and also adds an unnecessary "About" link. This behavior is causing confusion and inconsistencies in the navigation.

**Steps to Reproduce:**
1. Navigate to the home page.
2. Click on the "Home" link in the navigation menu.

**Expected Behavior:**
The "Home" link in the navigation menu should only navigate to the home page and not create duplicates or add an "About" link.

**Actual Behavior:**
Clicking on the "Home" link results in a new "Home" link appearing in the navigation, along with an "About" link.

**Video /Additional Information:**

https://github.com/Ayushgupta0207/HacktoberFest-2023/assets/142308041/ff08eb26-cc68-4ef8-b575-cc68cc26a301

**Comment by TOLU-MICH** [comment]
hi, please can you assign it to me

**Comment by Ayushgupta0207** [comment]
Hi @mohit-100 pls raise a PR against it

**Comment by Ayushgupta0207** [comment]
> hi, please can you assign it to me

Hi @TOLU-MICH please raise a valid PR against it.
