### ISSUE TITLE
Add a Random Quote Generator to the project.

### ISSUE THREAD

**Issue by arushitrivedi** [Ayushgupta0207/HacktoberFest-2023#37]
Hi @Ayushgupta0207! I want to contribute to your project by adding a Random Quote Generator, developed using HTML, CSS and Javascript. Please assign me to work on this issue under the "**hacktoberfest**" tag.

**Comment by Ayushgupta0207** [comment]
You can fork the repo, create the pull request with the code , I will merge in the repo.
