### ISSUE TITLE
Fibonacci.rs

### ISSUE THREAD

**Issue by ASHUdev05** [Ayushgupta0207/HacktoberFest-2023#45]
I would like to add the program for generating fibonacci numbers in the rust programming language.

**Comment by Shivam-Fl** [comment]
Assign this to me

**Comment by Ayushgupta0207** [comment]
@ASHUdev05 you can fork the repo , made the suitable changes and create the Pull Request

**Comment by Ayushgupta0207** [comment]
@Shivam-Fl same you can follow there is no process to asisgn
