### ISSUE TITLE
write a c++ program for finding second largest element in a array 

### ISSUE THREAD

**Issue by avishka45** [Ayushgupta0207/HacktoberFest-2023#48]
@Ayushgupta0207 pls assign this ASAP

**Comment by Ayushgupta0207** [comment]
@avishka45 , there is  no process to assign , you can fork the repo , make the suitable changes and create a valid PR

**Comment by avishka45** [comment]
> @avishka45 , there is no process to assign , you can fork the repo , make the suitable changes and create a valid PR

got it thanks
