### ISSUE TITLE
i can add a c++ Book alocation problem

### ISSUE THREAD

**Issue by Deepankar1484** [Ayushgupta0207/HacktoberFest-2023#51]
Hello @Ayushgupta0207 , Hope you are doing great today.
As some students are always confused in Book alocation problem i have got the easiest and fastest solution for the same.
please assign me the work and please add hacktober fest label.
I would be very thankful of yours.

**Comment by Ayushgupta0207** [comment]
@Deepankar1484 there is no process you can fork the repo , push your code and create a valid PR
